[scripts]
cl = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\CommandLineTools\\CommandLine\\cl.bat"
here = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\CommandLineTools\\CopyHere\\here.bat"
lines = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\CommandLineTools\\Lines\\lines\\lines.bat"
grep = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\CommandLineTools\\Grep\\grep.bat"
git = "C:\\Program Files\\Git\\cmd\\git.exe"
rye = "C:\\Users\\knuto\\rye\\shims\\rye.exe"

[shorthand]
pycli = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\CommandLineTools"
pyprot = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\Prototypes"
pytest = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\Tests"
pyr1 = "C:\\Users\\knuto\\Documents\\School\\VG2\\R1 - Python"
py = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python"
shell = "C:\\Users\\knuto\\Documents\\VisualStudioCode\\Python\\CommandLineTools\\CopyHere"
pylib = "C:\\\\Users\\\\knuto\\\\Documents\\\\VisualStudioCode\\\\Python\\\\Prototypes\\\\Libraries"

[shorthand.prefix]
symbol = "!"
